### ISSUE TITLE
Change `TapBooleansOps` closures to not take any argument

### ISSUE THREAD

**Issue by lcnr** [darfink/tap-rs#6]
I would like to change the following method signatures:
```rust
fn tap_true<R, F: FnOnce() -> R>(self, f: F) -> Self;
// instead of
fn tap_true<R, F: FnOnce(&mut bool) -> R>(self, f: F) -> Self;
```
and
```rust
fn tap_false<R, F: FnOnce() -> R>(self, f: F) -> Self;
// instead of
fn tap_false<R, F: FnOnce(&mut bool) -> R>(self, f: F) -> Self;
```
This would be similar to the way `TapOptionOps::tap_none` is currently implemented.

Changing a bool in tap can be quite misleading:
```rust
use tap::*;
let old = false;
assert_eq!(old.tap_false(|old| *old = true), true);
// old is still false
assert_eq!(old, false);
```

**Comment by darfink** [comment]
Yes, I'm inclined to agree. I also feel it's rather redundant.
Feel free to open a pull request, or I'll update this behavior in the near future.
